name = "the-stack"
main = ".output/server/index.mjs"
compatibility_date = "2025-03-25"
compatibility_flags = [ "nodejs_compat" ]
keep_vars = true

[assets]
binding = "ASSETS"
directory = ".output/public"

[observability]
enabled = true
